### ISSUE TITLE
Response is accepting negative json path variable [expected to fail]

### ISSUE THREAD

**Issue by nishamistry11** [qmetry/qaf-support-ws#10]
BDD step:
Given user requests '${post.nest.login}'
->Then response should have '$.*.results.abc' 
**Expected Result:** Response result should be containing proper key, if it does not contain key, then step should be failed
**Actual Result:**  BDD step is passing for negative validation.
Please find the below details:

**Method:** POST
**endpoint:** http://10.12.40.86/nest_security_testing/nativefw/services/login
**Response body:**
{
  "response": {
    "attributes": {
      "timestamp": "1524059369",
      "error": 0
    },
    "results": {
      "surveyNotificationFlag": 0,
      "isAdmin": 1,
      "isManager": 1,
      "isTravelAdmin": "IN",
      "location": "IN",
      "first_name": "Tushit",
      "last_name": "Shah",
      "job_title": "Accounts Executive",
      "displayPhoto": "",
      "token": "7ca8920e7e5848e44445a0e87efe1f46",
      "emp_id": "113"
    }
  }
}

**Comment by maruthmuthigi** [comment]
Please provide the request params too.

**Comment by naeem-github** [comment]
We are also facing same issue,
Problem is in hasJsonPath method from https://github.com/qmetry/qaf-support-ws/blob/master/src/com/qmetry/qaf/automation/step/WsStep.java class.

Response : 
`[
  {
    "userId": 1,
    "id": 1,
    "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
  },
  {
    "userId": 1,
    "id": 2,
    "title": "qui est esse",
    "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"
  },
  {
    "userId": 1,
    "id": 3,
    "title": "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    "body": "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut"
  },
  {
    "userId": 1,
    "id": 4,
    "title": "eum et est occaecati",
    "body": "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit"
  },
  {
    "userId": 1,
    "id": 5,
    "title": "nesciunt quas odio",
    "body": "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque"
  },
  {
    "userId": 1,
    "id": 6,
    "title": "dolorem eum magni eos aperiam quia",
    "body": "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae"
  },
  {
    "userId": 1,
    "id": 7,
    "title": "magnam facilis autem",
    "body": "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas"
  },
  {
    "userId": 1,
    "id": 8,
    "title": "dolorem dolore est ipsam",
    "body": "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae"
  },
  {
    "userId": 1,
    "id": 9,
    "title": "nesciunt iure omnis dolorem tempora et accusantium",
    "body": "consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas"
  },
  {
    "userId": 1,
    "id": 10,
    "title": "optio molestias id quia eum",
    "body": "quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error"
  }
]`

**Positive case** : 
And response should have '[*].userId'
Actual & Expected : Pass

**Negative case** : 
And response should have '[*].userId1'
Actual : Pass 
Expected : Fail

**Comment by mishalsmarsh** [comment]
I would suggest solution for above issue as below : 	if it is proper kindly take this code and merge to code
```
private static boolean hasJsonPath(String json, String path) {
		try {
			Object obj = JsonPath.read(json, path);
			if (StringUtil.isNotEmpty(path) && (path.contains("[*]"))) {
				if (obj instanceof List || obj instanceof ArrayList
						|| obj instanceof Array) {
					int list = ((List<?>) obj).size();
					if (list <= 0) {
						Reporter.log(
								"Response does not have this path::->" + path,
								MessageTypes.Info);
						return false;
					} else {
						return true;
					}
				}
			}
		} catch (Exception exception) {
			Reporter.log(exception.getMessage(), MessageTypes.Info);
			return false;
		}
		return true;
	}

```
cc @cjayswal  @naeem-github  @amitbhoraniya @nishamistry11
