### ISSUE TITLE
Getting the headers from reference into a request call appends the headers. Doesn't overwrite it.

### ISSUE THREAD

**Issue by Purva2710** [qmetry/qaf-support-ws#11]
**Sample Reference call**
\<template\>
\<baseurl\>\\</baseurl\>
\<headers\>
{"Content-type":"${content-type}",
"Accept":"${accept}"}
\</headers\>
\<paramters\>
{"content-type":"application/json",
"accept":"application/json"}
\</parameters\>
\</template\>

**Sample Request call**
\<reference\>template\</reference\>
\<method\>POST\</method\>
\<headers\>
{"Content-type":"application/json",
"Accept":"application/json"}
\</headers\>

**Expected result**
Client out-bound request
POST https://\<post url\>
Content-type: application/json, Accept:application/json

**Actual output**
Client out-bound request
POST https://\<post url\>
Content-type: application/json, application/json, Accept: application/json, application.json

**Comment by cjayswal** [comment]
This issue is not reproducible with latest (3.0.0) version.
