### ISSUE TITLE
License switch from GPL to MIT

### ISSUE THREAD

**Issue by cjayswal** [qmetry/qaf-support-ws#13]
Change the license to a more open license MIT.
We have to get the approval of every single committer or remove their code. All contributor as of today listed below:
Author:
@cjayswal

Contributors:
@mishalhshah
@infoneershalin 
@anjalibangoria
@amitbhoraniya 
@imjaypatel12

**Comment by amitbhoraniya** [comment]
@cjayswal - I agree to switch to MIT license.

**Comment by infoneershalin** [comment]
@cjayswal 
I agree to switch to MIT license.

**Comment by anjalibangoria** [comment]
@cjayswal  I agree to switch to MIT license.

**Comment by mishalhshah** [comment]
@cjayswal 
 I agree to switch to MIT license.
