### ISSUE TITLE
How to keep question character from URL's endpoint to not be encoded when sending the request?

### ISSUE THREAD

**Issue by zarashima** [qmetry/qaf-support-ws#15]
I have a Confluence API request which fetches the body's content page, URL is something like this: 
https://confluence.com/rest/api/content/12345678?expand=body.storage

When I use this endpoint: "/rest/api/content/12345678?expand=body.storage" as in the request call, then qaf WS will automatically translate the endpoint to `/rest/api/content/12345678%3Fexpand=body.storage` which in turns will throw 404 error . If question character is not encoded then it will be 200 which is expected

I want qaf WS step to do keep using question character rather than encoding it, any way to do so?

Thanks

**Comment by cjayswal** [comment]
try moving query parameter from `endpoint` to `query-parameters`. 
For example:
```
my.sample.req={'baseUrl':'${env.baseurl}', 'endPoint':'/rest/api/content/12345678', 'query-parameters':{'expand':'body.storage'}}
```
below is more readable:
```
my.sample.req={\
   'baseUrl':'${env.baseurl}',\
   'endPoint':'/rest/api/content/12345678',\
   'query-parameters':{\
       'expand':'body.storage'\
   }\
}
```

Refer [request call repository](https://github.com/qmetry/qaf-support-ws/wiki/Request-Call-Repository) documentation.

**Comment by zarashima** [comment]
Thanks, it works :)
